### ISSUE TITLE
unable to update Scenario Outlines on Jira

### ISSUE THREAD

**Issue by BlacktoBlue** [fundakol/behave-xray#23]
I have a test which is a Scenario outline:

e.g.
``` Scenario Outline: eating
  Given there are <start> cucumbers
  When I eat <eat> cucumbers
  Then I should have <left> cucumbers

  Examples:
    | start | eat | left |
    |    12 |   5 |    7 |
    |    20 |   5 |   15  |
```

When I run that as part of a test suite I get the following error:

```
Uploaded results to JIRA XRAY Test Execution: xx-1234
Exception IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\git\testing\windows-application-framework\venv\Scripts\behave.exe\__main__.py", line 7, in <module>
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave\__main__.py", line 183, in main
    return run_behave(config)
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave\__main__.py", line 127, in run_behave
    failed = runner.run()
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave\runner.py", line 804, in run
    return self.run_with_paths()
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave\runner.py", line 824, in run_with_paths
    return self.run_model()
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave\runner.py", line 626, in run_model
    failed = feature.run(self)
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave\model.py", line 350, in run
    formatter.eof()
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave_xray\formatter.py", line 221, in eof
    self.collect_tests()
  File "D:\git\testing\windows-application-framework\venv\lib\site-packages\behave_xray\formatter.py", line 235, in collect_tests
    testcase.status = self._get_xray_status(tc_status.statuses[0].name)
IndexError: list index out of range
```

**Comment by fundakol** [comment]
I cannot reproduce. Here is my outline scenario: https://github.com/fundakol/behave-xray/blob/b6a1035d5cd15f525bb2e1b7318633f088d8bbf3/tests/features/calculator.feature#L26-L34
which worked with this command:
`behave tests -f behave_xray:XrayCloudFormatter`

Did I miss something?
